### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by OR13** [peppelinux/draft-demarco-oauth-status-assertions#69]
```mermaid
sequenceDiagram
    Issuer-->>Holder: (credential issuance out of scope)
    Holder->>Issuer: application/status-assertion-request+jwt
    Issuer ->> Issuer : Status Check
    Issuer ->> Holder: application/status-assertion+jwt
    Holder -->> Verifier: (credential presentation out of scope)
```

[editable-link](https://mermaid.live/edit#pako:eNp9UTtPxDAM_iuWJxCt2DPcAgMMTCcxoCxW4nLh2iTnOELodP-dtFXFSyLTJ-d7-HFGlzyjwcKnytHxfaBXoclGaO-xlMrS97vdQxo9i4ErJ-w5aqARQvulJoFUFdIAxaXM16ty5TfhamGAch6DIw0p3hYlraWnUljmQi9zeNGbt3f9HgxNv0ED-0UFdwd2xz-srb__Yr7sVzbMg8EzSxjC79mycGlwMfo5H3Y4sUwUfNvaefazqAee2KJp0JMcLdp4aTyqmvYf0aFRqdxhzZ502zCagcbSquyDJnlaz7Bco8NM8SWljXP5BBcrkiI)

**Comment by peppelinux** [comment]
Included in the README, https://github.com/peppelinux/draft-demarco-oauth-status-assertions?tab=readme-ov-file#overview
