### ISSUE TITLE
Unlinkability and Reusability of Status Assertions

### ISSUE THREAD

**Issue by peppelinux** [peppelinux/draft-demarco-oauth-status-assertions#75]
Always Denis:

    Section 15.3. Unlinkability and Reusability of Status Assertions, the text states:

        This design is pivotal in ensuring unlinkability between Verifiers, where actions taken by one Verifier
        cannot be correlated or linked to actions taken by another. 

    This sentence sounds strange. An "action taken by one Verifier" will be invisible to another Verifier unless the network is unprotected,
    but it is assumed that TLS is being used. What is the problem for correlating "actions" taken by a Verifier ? This sentence would need to be reconsidered.

it says that since there are no fixed audiences in the status assertions, a verifier obtainign a status assertion cannot know if that assertion was already used with another verifier or any information usefull to track its usage and or its audience
 

    However, "unlinkability between Verifiers" usually means unlinkability between *colluding* Verifiers that shall not be able to know that a same end-user
    made an access to a protected resource.

    Using SD-JWT, such property can be supported if a SD-JWT are used only once. This should be mentioned in this section.

the same with the status assertions

**Comment by Denisthemalice** [comment]
> "the same with the status assertions". 

This is correct, but this should be mentioned in the draft and it is not mentioned

**Comment by peppelinux** [comment]
@Denisthemalice here the PR that aims to resolve this issue
https://github.com/peppelinux/draft-demarco-oauth-status-assertions/pull/80/files

**Comment by peppelinux** [comment]
please feel free to reopen this if you would like to add any additional remark
