### ISSUE TITLE
Align boolean validity claim

### ISSUE THREAD

**Issue by OR13** [peppelinux/draft-demarco-oauth-status-assertions#83]
We want to align the boolean validity claim with the status list approach.
This would mean dropping it in future versions, potentially.

Originally discussed in https://github.com/peppelinux/draft-demarco-oauth-status-assertions/pull/61

**Comment by peppelinux** [comment]
See: https://drafts.oauth.net/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#section-7.1
